@HostAddress = http://0.0.0.0:8000

### hello (get)
GET {{HostAddress}}/hello
Accept: application/json

{"data":"hello"}

### hello (post)
POST {{HostAddress}}/hello
Accept: application/json

{"data":"hello"}

### getInfo (post)
POST {{HostAddress}}/getInfo
Accept: application/json

{"data":"hello"}

### getInfo (post)
POST {{HostAddress}}/getInfo
Accept: application/json

{"data":"not hello"}

### (post) message job
POST {{HostAddress}}/put
Accept: application/json

{"data":"hello xdata team"}

### (post) pdf job
POST {{HostAddress}}/put
Accept: application/json

{"data":"hello xdata team", "jobType": "pdf2image"}