@HostAddress = http://0.0.0.0:8000

### hello (get)
GET {{HostAddress}}/hello
Accept: application/json

{"data":"hello"}

### hello (post)
POST {{HostAddress}}/hello
Accept: application/json

{"data":"hello"}

### getInfo (post)
POST {{HostAddress}}/getInfo
Accept: application/json

{"data":"hello"}

### getInfo (post)
POST {{HostAddress}}/getInfo
Accept: application/json

{"data":"not hello"}

### multi-thread message job
POST {{HostAddress}}/multiThread
Accept: application/json

{"data":"hello xdata team"}



### multi-thread pdf2image job
POST {{HostAddress}}/multiThread
Accept: application/json

{"data":"hello xdata team", "jobType": "pdf2image"}

### multi-process pdf2image
POST {{HostAddress}}/multiProcess
Accept: application/json

{"data":"hello xdata team"}

### (post) upload files and key/value pairs
POST {{HostAddress}}/uploadFiles
Accept: application/json
Content-Type: multipart/form-data; boundary=MyBoundary5d73155dbfd0c9661cc0a1cb7c2058a5

--MyBoundary5d73155dbfd0c9661cc0a1cb7c2058a5
Content-Disposition: form-data; name="data"

This is value of field[data] hello world!
--MyBoundary5d73155dbfd0c9661cc0a1cb7c2058a5
Content-Disposition: form-data; name="message"

This is value of field[message] Say hello to Tom and Edwood : >
--MyBoundary5d73155dbfd0c9661cc0a1cb7c2058a5
Content-Disposition: form-data; name="files"; filename="test.pdf"
Content-Type: application/octet-stream

< data/regal-17pages.pdf
--MyBoundary5d73155dbfd0c9661cc0a1cb7c2058a5
Content-Disposition: form-data; name="files"; filename="test-file-2.pdf"
Content-Type: application/octet-stream

< data/regal-17pages.pdf
--MyBoundary5d73155dbfd0c9661cc0a1cb7c2058a5--



### (post) payloadSimple
POST {{HostAddress}}/payloadSimple
Accept: application/json

{"id": "5d907f4e-81e9-426d-b7e4-d03965465d94", "messages": ["hello", "world"]}

### (post) payloadOptional - "extra" can be null|str, "extra2" can be missing 
POST {{HostAddress}}/payloadOptional
Accept: application/json

{"value": 1, "messages": ["hello", "world"], "extra":"extra data here!"}

### (post) payloadOptional - "extra" can be null|str, "extra2" can be missing 
POST {{HostAddress}}/payloadOptional
Accept: application/json

{"value": 1, "messages": ["hello", "world"], "extra":null, "extra2": "yes"}


### (post) payloadFull - nested payload
POST {{HostAddress}}/payloadFull
Accept: application/json

{
  "header": {"id": "5d907f4e-81e9-426d-b7e4-d03965465d94", "messages": ["hello", "world"]},
  "data":  {"value": 1, "messages": ["hello", "world"], "extra":null, "extra2": "yes"}
}

